//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRegistartion.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblICard
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public string DOB { get; set; }
        public string Expierd { get; set; }
        public string Photo { get; set; }
    }
}
