//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRegistartion.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        public int ID { get; set; }
        public string ProdName { get; set; }
        public string Price { get; set; }
        public string Contact { get; set; }
        public string Image { get; set; }
        public string CompanyName { get; set; }
    }
}
